# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-27 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_book_num_pages'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_review',
            field=models.TextField(null=True),
        ),
    ]
