# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-28 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_auto_20160428_1446'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='my_works',
        ),
    ]
